# Файл конфигурации Detekt
# https://detekt.dev/docs/rules/formatting/
# https://github.com/detekt/detekt/tree/v1.19.0

processors:
  active: true
  exclude:
    - 'FunctionCountProcessor'
    - 'PropertyCountProcessor'
    - 'ClassCountProcessor'
    - 'PackageCountProcessor'
    - 'KtFileCountProcessor'

config:
  validation: true

# Включение стандартных правил
style:
  active: true
  MagicNumber:
    active: true
    ignoreNumbers: "-1,0,1,2"
  MaxLineLength:
    active: true
    maxLineLength: 100
  OptionalUnit:
    active: true
  ReturnCount:
    active: true
    max: 3
  SafeCast:
    active: true
  UseIfEmptyOrIfBlank:
    active: true
  UseIsNullOrEmpty:
    active: true
  ClassOrdering:
    active: true
  CollapsibleIfStatements:
    active: true
  MayBeConst:
    active: true
  UnnecessaryLet:
    active: true
  VarCouldBeVal:
    active: true



complexity:
  active: true
  LargeClass:
    active: true
    threshold: 600
  LongMethod:
    active: true
    threshold: 30
  ComplexMethod:
    active: true
    threshold: 15

naming:
  active: true
  ClassNaming:
    active: true
    classPattern: '^[A-Z][a-zA-Z0-9]*$'
  FunctionNaming:
    active: true
    functionPattern: '^[a-z][a-zA-Z0-9]*$'
  VariableNaming:
    active: true
    variablePattern: '^[a-z][a-zA-Z0-9]*$'

comments:
  active: true
  CommentOverPrivateFunction:
    active: true

# Включение правил потенциальных ошибок
potential-bugs:
  active: true
  UnsafeCast:
    active: true
  UnsafeCallOnNullableType:
    active: true
  CastToNullableType:
    active: true
  DontDowncastCollectionTypes:
    active: true
  DoubleMutabilityForCollection:
    active: true
  EqualsAlwaysReturnsTrueOrFalse:
    active: true
  IgnoredReturnValue:
    active: true
  MapGetWithNotNullAssertionOperator:
    active: true
  MissingWhenCase:
    active: true

# Включение правил производительности
performance:
  active: true
  SpreadOperator:
    active: true
  ForEachOnRange:
    active: true
  UnnecessaryTemporaryInstantiation:
    active: true

# Включение правил форматирования
formatting:
  active: true
  android: false
  autoCorrect: true
  ChainWrapping:
    active: true
    autoCorrect: true
  CommentSpacing:
    active: true
    autoCorrect: true
  Filename:
    active: true
  FinalNewline:
    active: true
    autoCorrect: true
  ImportOrdering:
    active: false
  Indentation:
    active: true
    autoCorrect: true
    indentSize: 4
    continuationIndentSize: 4
  MaximumLineLength:
    active: true
    maxLineLength: 160
  ModifierOrdering:
    active: true
    autoCorrect: true
  NoBlankLineBeforeRbrace:
    active: true
    autoCorrect: true
  NoConsecutiveBlankLines:
    active: true
    autoCorrect: true
  NoEmptyClassBody:
    active: true
    autoCorrect: true
  NoItParamInMultilineLambda:
    active: false
  NoLineBreakAfterElse:
    active: true
    autoCorrect: true
  NoLineBreakBeforeAssignment:
    active: true
    autoCorrect: true
  NoMultipleSpaces:
    active: true
    autoCorrect: true
  NoSemicolons:
    active: true
    autoCorrect: true
  NoTrailingSpaces:
    active: true
    autoCorrect: true
  NoUnitReturn:
    active: true
    autoCorrect: true
  NoUnusedImports:
    active: true
    autoCorrect: true
  NoWildcardImports:
    active: true
    autoCorrect: true
  PackageName:
    active: true
    autoCorrect: true
  ParameterListWrapping:
    active: true
    autoCorrect: true
    indentSize: 4
  SpacingAroundColon:
    active: true
    autoCorrect: true
  SpacingAroundComma:
    active: true
    autoCorrect: true
  SpacingAroundCurly:
    active: true
    autoCorrect: true
  SpacingAroundKeyword:
    active: true
    autoCorrect: true
  SpacingAroundOperators:
    active: true
    autoCorrect: true
  SpacingAroundParens:
    active: true
    autoCorrect: true
  SpacingAroundRangeOperator:
    active: true
    autoCorrect: true
  StringTemplate:
    active: true
    autoCorrect: true
  NoEmptyFirstLineInMethodBlock:
    active: true
    autoCorrect: true
  Wrapping:
    active: true
    autoCorrect: true
  MultiLineIfElse:
    active: true
    autoCorrect: true
  BracesOnIfStatements:
    active: true
    autoCorrect: true


# Включение правил для неиспользуемого кода
empty-blocks:
  active: true
  EmptyCatchBlock:
    active: true
  EmptyIfBlock:
    active: true
  EmptyElseBlock:
    active: true
  EmptyForBlock:
    active: true
  EmptyWhileBlock:
    active: true
  EmptyDoWhileBlock:
    active: true
  EmptyFunctionBlock:
    active: true
  EmptyClassBlock:
    active: true

# Настройки для уменьшения дублирующихся предупреждений
console-reports:
  active: true
  exclude:
    - 'ComplexityReport'
    - 'ProjectStatistics'